import { AdapterErrorCode, VSRepoAdapterError } from "vsrepo";

/**
 * Valida o client Prisma passado como primeiro argumento do construtor do
 * `VSRepoPrisma7Adapter`. Roda depois da config já ter sido validada (usa o
 * `tableName` validado), e falha cedo — com um `VSRepoAdapterError` claro —
 * em vez de deixar o adapter quebrar mais tarde, na primeira query, com um
 * erro genérico de runtime (`Cannot read properties of undefined`, etc.):
 *
 * - `prisma` não pode ser `null`/`undefined` (code `MISSING_DB_CLIENT`);
 * - `prisma[tableName]` precisa existir como delegate (ex. `prisma.user`
 *   para `tableName: "user"`) (code `MODEL_NOT_FOUND`), pegando erros de
 *   digitação em `tableName` — ou um `tableName` que não corresponde a
 *   nenhum model do schema Prisma — no construtor, não numa query.
 */
export function validatePrismaClient(prisma: unknown, tableName: string): void {
    if (prisma === null || prisma === undefined) {
        throw new VSRepoAdapterError(
            "Missing Prisma client: the first constructor argument (prisma) is null/undefined.",
            AdapterErrorCode.MISSING_DB_CLIENT,
            null,
        );
    }

    const delegate = (prisma as Record<string, unknown>)[tableName];

    if (typeof delegate !== "object" || delegate === null) {
        throw new VSRepoAdapterError(
            `Invalid constructor config (tableName): no delegate found for '${tableName}' on the provided Prisma client ` +
                `(expected 'prisma.${tableName}' to exist — check that '${tableName}' matches a model name generated by Prisma).`,
            AdapterErrorCode.MODEL_NOT_FOUND,
            null,
        );
    }
}
